;;; my-theme-palette.el --- Shared color palettes for my-light and my-dark themes -*- lexical-binding: t; -*-

;;; Commentary:
;;
;; Provides `my-theme-palette', which returns an alist of semantic color
;; names for a given variant (light or dark).  Both my-light-theme.el
;; and my-dark-theme.el require this module so that color data is
;; defined once and shared.

;;; Code:

(defun my-theme-palette--light ()
  "Return the light color palette alist."
  '(;; --- Base ---
    (bg              . "#FFFFFF")
    (bg-alt          . "#F7F7F7")
    (bg-highlight    . "#FFFFCC")
    (bg-region       . "#B4D5FE")
    (bg-paren-match  . "#99CCFF")
    (bg-paren-mismatch . "#FF6666")
    (bg-isearch      . "#FFFF00")
    (bg-lazy-isearch . "#CCFFCC")
    (bg-hl-line      . "#EFEFEF")
    (fg              . "#333333")
    (fg-alt          . "#555555")
    (fg-dim          . "#999999")
    (fg-faint        . "#BBBBBB")
    (cursor          . "#000000")

    ;; --- Syntax ---
    (keyword         . "#0000FF")
    (string          . "#008000")
    (comment         . "#8D8D84")
    (doc             . "#036A07")
    (variable        . "#BA36A5")
    (function-name   . "#006699")
    (type            . "#6434A3")
    (constant        . "#D0372D")
    (builtin         . "#006FE0")
    (preprocessor    . "#808080")
    (negation        . "#FF0000")
    (warning         . "#FF6600")
    (error           . "#FF0000")
    (success         . "#008000")
    (info            . "#006FE0")

    ;; --- Links ---
    (link            . "#006DAF")
    (link-visited    . "#8B008B")

    ;; --- Mode line ---
    (ml-active-bg    . "#335EA8")
    (ml-active-fg    . "#FFFFFF")
    (ml-inactive-bg  . "#9B9C97")
    (ml-inactive-fg  . "#F0F0EF")

    ;; --- Diff / VCS ---
    (diff-added-bg   . "#DDFFDD")
    (diff-added-fg   . "#22863A")
    (diff-removed-bg . "#FFDDDD")
    (diff-removed-fg . "#B31D28")
    (diff-changed-bg . "#FFF3CE")
    (diff-changed-fg . "#B08800")
    (diff-hunk-bg    . "#E0E7FF")
    (diff-hunk-fg    . "#335EA8")
    (diff-fine-added . "#AAFFAA")
    (diff-fine-removed . "#FFAAAA")
    (diff-indicator-added . "#22863A")
    (diff-indicator-removed . "#B31D28")

    ;; --- Org mode ---
    (ol1-bg          . "#E0E0E0")
    (ol1-fg          . "#3C3C3C")
    (ol2-bg          . "#DDEEFF")
    (ol2-fg          . "#123555")
    (ol3-bg          . "#DDFEDD")
    (ol3-fg          . "#005522")
    (ol4-fg          . "#E3258D")
    (ol5-fg          . "#0077CC")
    (ol6-fg          . "#2EAE2C")
    (ol7-fg          . "#FD8008")
    (ol8-fg          . "#8B8989")
    (org-todo-fg     . "#FF6347")
    (org-done-fg     . "#008000")
    (org-block-bg    . "#FFFFEA")
    (org-code-bg     . "#F5F5F5")
    (org-code-fg     . "#7F0055")
    (org-table-bg    . "#E8E5D5")
    (org-date-fg     . "#6434A3")
    (org-tag-fg      . "#AAAAAA")
    (org-drawer-fg   . "#0000FF")

    ;; --- Outline / Markdown ---
    (outline-1       . "#3C3C3C")
    (outline-2       . "#123555")
    (outline-3       . "#005522")
    (outline-4       . "#E3258D")
    (outline-5       . "#0077CC")
    (outline-6       . "#2EAE2C")
    (outline-7       . "#FD8008")
    (outline-8       . "#8B8989")

    ;; --- Company ---
    (company-bg      . "#F0F0F0")
    (company-fg      . "#333333")
    (company-sel-bg  . "#B4D5FE")
    (company-sel-fg  . "#000000")
    (company-border  . "#CCCCCC")

    ;; --- Flycheck / Flyspell ---
    (flycheck-error-bg . "#FFDDDD")
    (flycheck-warn-bg  . "#FFFFCC")
    (flycheck-info-bg  . "#DDFFDD")

    ;; --- Rainbow delimiters ---
    (rainbow-1       . "#707183")
    (rainbow-2       . "#7388D6")
    (rainbow-3       . "#909183")
    (rainbow-4       . "#709870")
    (rainbow-5       . "#907373")
    (rainbow-6       . "#6276BA")
    (rainbow-7       . "#858580")
    (rainbow-8       . "#80A880")
    (rainbow-9       . "#887070")

    ;; --- ANSI colors ---
    (ansi-black      . "#000000")
    (ansi-red        . "#CC0000")
    (ansi-green      . "#00CC00")
    (ansi-yellow     . "#CCCC00")
    (ansi-blue       . "#0000CC")
    (ansi-magenta    . "#CC00CC")
    (ansi-cyan       . "#00CCCC")
    (ansi-white      . "#CCCCCC")
    (ansi-bright-black   . "#555555")
    (ansi-bright-red     . "#FF0000")
    (ansi-bright-green   . "#00FF00")
    (ansi-bright-yellow  . "#FFFF00")
    (ansi-bright-blue    . "#0000FF")
    (ansi-bright-magenta . "#FF00FF")
    (ansi-bright-cyan    . "#00FFFF")
    (ansi-bright-white   . "#FFFFFF")

    ;; --- OCaml / Tuareg ---
    (tuareg-governing   . "#00688B")
    (tuareg-multistage  . "#7F007F")
    (tuareg-operator    . "#8B6508")
    (tuareg-module      . "#6434A3")
    (tuareg-constructor . "#2F4F4F")
    (tuareg-label       . "#8B4513")
    (tuareg-double-semi . "#CD3700")
    (tuareg-error       . "#FF0000")
    (tuareg-interactive-output    . "#006400")
    (tuareg-interactive-error     . "#8B0000")
    (tuareg-interactive-directive . "#0000CD")
    (tuareg-attribute        . "#808080")
    (tuareg-extension-node   . "#6B8E23")
    (tuareg-doc-markup       . "#8B008B")
    (tuareg-doc-verbatim     . "#005F5F")
    (tuareg-line-number      . "#999999")
    (tuareg-opam-error       . "#FF0000")
    (tuareg-opam-pkg-variable . "#BA36A5")

    ;; --- Merlin ---
    (merlin-type       . "#E8F0FF")
    (merlin-warn       . "#FFE0B2")
    (merlin-error      . "#FFCCCC")

    ;; --- UTop ---
    (utop-prompt       . "#0000FF")
    (utop-stdout       . "#333333")
    (utop-stderr       . "#CC0000")
    (utop-frozen       . "#808080")
    (utop-error        . "#FF0000")

    ;; --- Misc ---
    (shadow            . "#999999")
    (line-number       . "#999999")
    (line-number-current . "#333333")
    (tooltip-bg        . "#FFFFCC")
    (tooltip-fg        . "#333333")
    (header-line-bg    . "#F0F0F0")
    (header-line-fg    . "#333333")
    (whitespace        . "#E8E8E8")
    (trailing-ws       . "#FFBFBF")
    (escape-glyph      . "#FF6600")
    (minibuffer-prompt  . "#335EA8")
    (fringe            . "#F7F7F7")
    (vertical-border   . "#CCCCCC")
    (yas-field         . "#E5F4FF")

    ;; --- Ediff ---
    (ediff-current-a   . "#FFDDDD")
    (ediff-current-b   . "#DDFFDD")
    (ediff-current-c   . "#FFFFAA")
    (ediff-fine-a      . "#FFAAAA")
    (ediff-fine-b      . "#AAFFAA")
    (ediff-fine-c      . "#FFFF55")
    (ediff-even        . "#F0F0F0")
    (ediff-odd         . "#E0E0E0")

    ;; --- Magit ---
    (magit-section-bg  . "#F0F0F0")
    (magit-section-fg  . "#333333")
    (magit-branch-local  . "#006FE0")
    (magit-branch-remote . "#008000")
    (magit-tag         . "#D0372D")

    ;; --- Dired ---
    (dired-directory   . "#0000FF")
    (dired-header      . "#006FE0")
    (dired-symlink     . "#008B8B")
    (dired-mark        . "#FF0000")

    ;; --- Compilation / Grep ---
    (comp-error        . "#FF0000")
    (comp-warning      . "#FF6600")
    (comp-info         . "#008000")
    (comp-line-number  . "#6434A3")
    (grep-match        . "#FFFF00")
    (grep-file         . "#6434A3")
    (grep-line         . "#D0372D")

    ;; --- LSP ---
    (lsp-face-highlight . "#E8F0FF")

    ;; --- Calendar ---
    (calendar-today    . "#0000FF")
    (calendar-holiday  . "#FF0000")

    ;; --- Speedbar ---
    (speedbar-file     . "#006699")
    (speedbar-dir      . "#0000FF")
    (speedbar-tag      . "#8B4513")
    (speedbar-selected . "#FF0000")
    (speedbar-highlight . "#EEEEEE")

    ;; --- Gnus / Message ---
    (gnus-group-1      . "#006FE0")
    (gnus-group-2      . "#008000")
    (gnus-group-3      . "#6434A3")
    (gnus-header-from  . "#006699")
    (gnus-header-subject . "#0000FF")
    (gnus-header-name  . "#8B4513")
    (gnus-header-content . "#006400")
    (gnus-summary-selected . "#0000FF")
    (gnus-summary-normal . "#333333")
    (gnus-cite-1       . "#006699")
    (gnus-cite-2       . "#008000")
    (gnus-cite-3       . "#6434A3")
    (message-header-name . "#8B4513")
    (message-header-to   . "#006699")
    (message-header-cc   . "#006400")
    (message-header-other . "#006FE0")
    (message-header-subject . "#0000FF")
    (message-separator  . "#999999")))

(defun my-theme-palette--dark ()
  "Return the dark color palette alist."
  '(;; --- Base ---
    (bg              . "#1a1a2e")
    (bg-alt          . "#16213e")
    (bg-highlight    . "#2a2a4a")
    (bg-region       . "#3d4f7c")
    (bg-paren-match  . "#3d5f8c")
    (bg-paren-mismatch . "#6e2020")
    (bg-isearch      . "#5c5c00")
    (bg-lazy-isearch . "#1a3a1a")
    (bg-hl-line      . "#1e1e3a")
    (fg              . "#d0cdd3")
    (fg-alt          . "#b0adb3")
    (fg-dim          . "#7a7880")
    (fg-faint        . "#555560")
    (cursor          . "#e0af68")

    ;; --- Syntax ---
    (keyword         . "#7aa2f7")
    (string          . "#9ece6a")
    (comment         . "#565f89")
    (doc             . "#6a9955")
    (variable        . "#bb9af7")
    (function-name   . "#e0af68")
    (type            . "#2ac3de")
    (constant        . "#ff9e64")
    (builtin         . "#7dcfff")
    (preprocessor    . "#737aa2")
    (negation        . "#f7768e")
    (warning         . "#e0af68")
    (error           . "#f7768e")
    (success         . "#9ece6a")
    (info            . "#7dcfff")

    ;; --- Links ---
    (link            . "#7aa2f7")
    (link-visited    . "#bb9af7")

    ;; --- Mode line ---
    (ml-active-bg    . "#3d4f7c")
    (ml-active-fg    . "#d0cdd3")
    (ml-inactive-bg  . "#2a2a4a")
    (ml-inactive-fg  . "#565f89")

    ;; --- Diff / VCS ---
    (diff-added-bg   . "#1a2e1a")
    (diff-added-fg   . "#9ece6a")
    (diff-removed-bg . "#2e1a1a")
    (diff-removed-fg . "#f7768e")
    (diff-changed-bg . "#2e2a1a")
    (diff-changed-fg . "#e0af68")
    (diff-hunk-bg    . "#1a1a3e")
    (diff-hunk-fg    . "#7aa2f7")
    (diff-fine-added . "#2a4a2a")
    (diff-fine-removed . "#4a2a2a")
    (diff-indicator-added . "#9ece6a")
    (diff-indicator-removed . "#f7768e")

    ;; --- Org mode ---
    (ol1-bg          . "#2a2a4a")
    (ol1-fg          . "#d0cdd3")
    (ol2-bg          . "#1a2a4e")
    (ol2-fg          . "#7aa2f7")
    (ol3-bg          . "#1a2e2a")
    (ol3-fg          . "#9ece6a")
    (ol4-fg          . "#f7768e")
    (ol5-fg          . "#7dcfff")
    (ol6-fg          . "#9ece6a")
    (ol7-fg          . "#ff9e64")
    (ol8-fg          . "#737aa2")
    (org-todo-fg     . "#f7768e")
    (org-done-fg     . "#9ece6a")
    (org-block-bg    . "#16213e")
    (org-code-bg     . "#1e1e3a")
    (org-code-fg     . "#ff9e64")
    (org-table-bg    . "#1e1e3a")
    (org-date-fg     . "#bb9af7")
    (org-tag-fg      . "#565f89")
    (org-drawer-fg   . "#7aa2f7")

    ;; --- Outline / Markdown ---
    (outline-1       . "#d0cdd3")
    (outline-2       . "#7aa2f7")
    (outline-3       . "#9ece6a")
    (outline-4       . "#f7768e")
    (outline-5       . "#7dcfff")
    (outline-6       . "#9ece6a")
    (outline-7       . "#ff9e64")
    (outline-8       . "#737aa2")

    ;; --- Company ---
    (company-bg      . "#16213e")
    (company-fg      . "#d0cdd3")
    (company-sel-bg  . "#3d4f7c")
    (company-sel-fg  . "#FFFFFF")
    (company-border  . "#3d4f7c")

    ;; --- Flycheck / Flyspell ---
    (flycheck-error-bg . "#2e1a1a")
    (flycheck-warn-bg  . "#2e2a1a")
    (flycheck-info-bg  . "#1a2e1a")

    ;; --- Rainbow delimiters ---
    (rainbow-1       . "#9ca0b0")
    (rainbow-2       . "#7aa2f7")
    (rainbow-3       . "#9ece6a")
    (rainbow-4       . "#e0af68")
    (rainbow-5       . "#f7768e")
    (rainbow-6       . "#bb9af7")
    (rainbow-7       . "#2ac3de")
    (rainbow-8       . "#ff9e64")
    (rainbow-9       . "#7dcfff")

    ;; --- ANSI colors ---
    (ansi-black      . "#1a1a2e")
    (ansi-red        . "#f7768e")
    (ansi-green      . "#9ece6a")
    (ansi-yellow     . "#e0af68")
    (ansi-blue       . "#7aa2f7")
    (ansi-magenta    . "#bb9af7")
    (ansi-cyan       . "#7dcfff")
    (ansi-white      . "#d0cdd3")
    (ansi-bright-black   . "#565f89")
    (ansi-bright-red     . "#ff99a8")
    (ansi-bright-green   . "#b9e87a")
    (ansi-bright-yellow  . "#f0cf88")
    (ansi-bright-blue    . "#9ab8ff")
    (ansi-bright-magenta . "#d0b0ff")
    (ansi-bright-cyan    . "#99dfff")
    (ansi-bright-white   . "#FFFFFF")

    ;; --- OCaml / Tuareg ---
    (tuareg-governing   . "#7dcfff")
    (tuareg-multistage  . "#bb9af7")
    (tuareg-operator    . "#c0a36e")
    (tuareg-module      . "#bb9af7")
    (tuareg-constructor . "#73daca")
    (tuareg-label       . "#e0af68")
    (tuareg-double-semi . "#f08070")
    (tuareg-error       . "#f7768e")
    (tuareg-interactive-output    . "#9ece6a")
    (tuareg-interactive-error     . "#f7768e")
    (tuareg-interactive-directive . "#7aa2f7")
    (tuareg-attribute        . "#737aa2")
    (tuareg-extension-node   . "#9ece6a")
    (tuareg-doc-markup       . "#bb9af7")
    (tuareg-doc-verbatim     . "#2ac3de")
    (tuareg-line-number      . "#565f89")
    (tuareg-opam-error       . "#f7768e")
    (tuareg-opam-pkg-variable . "#bb9af7")

    ;; --- Merlin ---
    (merlin-type       . "#2a2a5e")
    (merlin-warn       . "#3e2e1a")
    (merlin-error      . "#3e1a1a")

    ;; --- UTop ---
    (utop-prompt       . "#7aa2f7")
    (utop-stdout       . "#d0cdd3")
    (utop-stderr       . "#f7768e")
    (utop-frozen       . "#565f89")
    (utop-error        . "#f7768e")

    ;; --- Misc ---
    (shadow            . "#565f89")
    (line-number       . "#3b3b55")
    (line-number-current . "#d0cdd3")
    (tooltip-bg        . "#16213e")
    (tooltip-fg        . "#d0cdd3")
    (header-line-bg    . "#16213e")
    (header-line-fg    . "#d0cdd3")
    (whitespace        . "#2a2a4a")
    (trailing-ws       . "#4a2020")
    (escape-glyph      . "#ff9e64")
    (minibuffer-prompt  . "#7aa2f7")
    (fringe            . "#1a1a2e")
    (vertical-border   . "#3d4f7c")
    (yas-field         . "#1a2a4e")

    ;; --- Ediff ---
    (ediff-current-a   . "#2e1a1a")
    (ediff-current-b   . "#1a2e1a")
    (ediff-current-c   . "#2e2a1a")
    (ediff-fine-a      . "#4a2a2a")
    (ediff-fine-b      . "#2a4a2a")
    (ediff-fine-c      . "#4a4a1a")
    (ediff-even        . "#1e1e3a")
    (ediff-odd         . "#2a2a4a")

    ;; --- Magit ---
    (magit-section-bg  . "#1e1e3a")
    (magit-section-fg  . "#d0cdd3")
    (magit-branch-local  . "#7aa2f7")
    (magit-branch-remote . "#9ece6a")
    (magit-tag         . "#ff9e64")

    ;; --- Dired ---
    (dired-directory   . "#7aa2f7")
    (dired-header      . "#7dcfff")
    (dired-symlink     . "#2ac3de")
    (dired-mark        . "#f7768e")

    ;; --- Compilation / Grep ---
    (comp-error        . "#f7768e")
    (comp-warning      . "#e0af68")
    (comp-info         . "#9ece6a")
    (comp-line-number  . "#bb9af7")
    (grep-match        . "#5c5c00")
    (grep-file         . "#bb9af7")
    (grep-line         . "#ff9e64")

    ;; --- LSP ---
    (lsp-face-highlight . "#2a2a5e")

    ;; --- Calendar ---
    (calendar-today    . "#7aa2f7")
    (calendar-holiday  . "#f7768e")

    ;; --- Speedbar ---
    (speedbar-file     . "#e0af68")
    (speedbar-dir      . "#7aa2f7")
    (speedbar-tag      . "#9ece6a")
    (speedbar-selected . "#f7768e")
    (speedbar-highlight . "#2a2a4a")

    ;; --- Gnus / Message ---
    (gnus-group-1      . "#7aa2f7")
    (gnus-group-2      . "#9ece6a")
    (gnus-group-3      . "#bb9af7")
    (gnus-header-from  . "#e0af68")
    (gnus-header-subject . "#7aa2f7")
    (gnus-header-name  . "#9ece6a")
    (gnus-header-content . "#2ac3de")
    (gnus-summary-selected . "#7aa2f7")
    (gnus-summary-normal . "#d0cdd3")
    (gnus-cite-1       . "#e0af68")
    (gnus-cite-2       . "#9ece6a")
    (gnus-cite-3       . "#bb9af7")
    (message-header-name . "#9ece6a")
    (message-header-to   . "#e0af68")
    (message-header-cc   . "#2ac3de")
    (message-header-other . "#7dcfff")
    (message-header-subject . "#7aa2f7")
    (message-separator  . "#565f89")))

(defun my-theme-palette--light-256 ()
  "Return the light 256-color palette alist.
Uses xterm-256 `color-NNN' names for terminals without true color."
  '(;; --- Base ---
    (bg              . "white")
    (bg-alt          . "color-255")
    (bg-highlight    . "color-229")
    (bg-region       . "color-153")
    (bg-paren-match  . "color-117")
    (bg-paren-mismatch . "color-196")
    (bg-isearch      . "yellow")
    (bg-lazy-isearch . "color-194")
    (bg-hl-line      . "color-254")
    (fg              . "color-236")
    (fg-alt          . "color-240")
    (fg-dim          . "color-246")
    (fg-faint        . "color-250")
    (cursor          . "black")

    ;; --- Syntax ---
    (keyword         . "blue")
    (string          . "color-28")
    (comment         . "color-245")
    (doc             . "color-22")
    (variable        . "color-133")
    (function-name   . "color-30")
    (type            . "color-56")
    (constant        . "color-160")
    (builtin         . "color-33")
    (preprocessor    . "color-244")
    (negation        . "red")
    (warning         . "color-208")
    (error           . "red")
    (success         . "color-28")
    (info            . "color-33")

    ;; --- Links ---
    (link            . "color-32")
    (link-visited    . "color-90")

    ;; --- Mode line ---
    (ml-active-bg    . "color-61")
    (ml-active-fg    . "white")
    (ml-inactive-bg  . "color-247")
    (ml-inactive-fg  . "color-255")

    ;; --- Diff / VCS ---
    (diff-added-bg   . "color-194")
    (diff-added-fg   . "color-28")
    (diff-removed-bg . "color-224")
    (diff-removed-fg . "color-124")
    (diff-changed-bg . "color-230")
    (diff-changed-fg . "color-136")
    (diff-hunk-bg    . "color-189")
    (diff-hunk-fg    . "color-61")
    (diff-fine-added . "color-157")
    (diff-fine-removed . "color-217")
    (diff-indicator-added . "color-28")
    (diff-indicator-removed . "color-124")

    ;; --- Org mode ---
    (ol1-bg          . "color-253")
    (ol1-fg          . "color-237")
    (ol2-bg          . "color-189")
    (ol2-fg          . "color-24")
    (ol3-bg          . "color-194")
    (ol3-fg          . "color-22")
    (ol4-fg          . "color-162")
    (ol5-fg          . "color-32")
    (ol6-fg          . "color-34")
    (ol7-fg          . "color-208")
    (ol8-fg          . "color-245")
    (org-todo-fg     . "color-203")
    (org-done-fg     . "color-28")
    (org-block-bg    . "color-230")
    (org-code-bg     . "color-255")
    (org-code-fg     . "color-89")
    (org-table-bg    . "color-223")
    (org-date-fg     . "color-56")
    (org-tag-fg      . "color-248")
    (org-drawer-fg   . "blue")

    ;; --- Outline / Markdown ---
    (outline-1       . "color-237")
    (outline-2       . "color-24")
    (outline-3       . "color-22")
    (outline-4       . "color-162")
    (outline-5       . "color-32")
    (outline-6       . "color-34")
    (outline-7       . "color-208")
    (outline-8       . "color-245")

    ;; --- Company ---
    (company-bg      . "color-254")
    (company-fg      . "color-236")
    (company-sel-bg  . "color-153")
    (company-sel-fg  . "black")
    (company-border  . "color-250")

    ;; --- Flycheck / Flyspell ---
    (flycheck-error-bg . "color-224")
    (flycheck-warn-bg  . "color-229")
    (flycheck-info-bg  . "color-194")

    ;; --- Rainbow delimiters ---
    (rainbow-1       . "color-243")
    (rainbow-2       . "color-68")
    (rainbow-3       . "color-247")
    (rainbow-4       . "color-65")
    (rainbow-5       . "color-95")
    (rainbow-6       . "color-62")
    (rainbow-7       . "color-246")
    (rainbow-8       . "color-71")
    (rainbow-9       . "color-94")

    ;; --- ANSI colors ---
    (ansi-black      . "black")
    (ansi-red        . "color-160")
    (ansi-green      . "color-34")
    (ansi-yellow     . "color-184")
    (ansi-blue       . "color-20")
    (ansi-magenta    . "color-164")
    (ansi-cyan       . "color-37")
    (ansi-white      . "color-250")
    (ansi-bright-black   . "color-240")
    (ansi-bright-red     . "red")
    (ansi-bright-green   . "color-46")
    (ansi-bright-yellow  . "yellow")
    (ansi-bright-blue    . "blue")
    (ansi-bright-magenta . "magenta")
    (ansi-bright-cyan    . "cyan")
    (ansi-bright-white   . "white")

    ;; --- OCaml / Tuareg ---
    (tuareg-governing   . "color-30")
    (tuareg-multistage  . "color-90")
    (tuareg-operator    . "color-136")
    (tuareg-module      . "color-56")
    (tuareg-constructor . "color-23")
    (tuareg-label       . "color-94")
    (tuareg-double-semi . "color-166")
    (tuareg-error       . "red")
    (tuareg-interactive-output    . "color-22")
    (tuareg-interactive-error     . "color-88")
    (tuareg-interactive-directive . "color-20")
    (tuareg-attribute        . "color-244")
    (tuareg-extension-node   . "color-64")
    (tuareg-doc-markup       . "color-90")
    (tuareg-doc-verbatim     . "color-23")
    (tuareg-line-number      . "color-246")
    (tuareg-opam-error       . "red")
    (tuareg-opam-pkg-variable . "color-133")

    ;; --- Merlin ---
    (merlin-type       . "color-189")
    (merlin-warn       . "color-223")
    (merlin-error      . "color-224")

    ;; --- UTop ---
    (utop-prompt       . "blue")
    (utop-stdout       . "color-236")
    (utop-stderr       . "color-160")
    (utop-frozen       . "color-244")
    (utop-error        . "red")

    ;; --- Misc ---
    (shadow            . "color-246")
    (line-number       . "color-246")
    (line-number-current . "color-236")
    (tooltip-bg        . "color-229")
    (tooltip-fg        . "color-236")
    (header-line-bg    . "color-254")
    (header-line-fg    . "color-236")
    (whitespace        . "color-253")
    (trailing-ws       . "color-217")
    (escape-glyph      . "color-208")
    (minibuffer-prompt  . "color-61")
    (fringe            . "color-255")
    (vertical-border   . "color-250")
    (yas-field         . "color-153")

    ;; --- Ediff ---
    (ediff-current-a   . "color-224")
    (ediff-current-b   . "color-194")
    (ediff-current-c   . "color-229")
    (ediff-fine-a      . "color-217")
    (ediff-fine-b      . "color-157")
    (ediff-fine-c      . "color-227")
    (ediff-even        . "color-254")
    (ediff-odd         . "color-253")

    ;; --- Magit ---
    (magit-section-bg  . "color-254")
    (magit-section-fg  . "color-236")
    (magit-branch-local  . "color-33")
    (magit-branch-remote . "color-28")
    (magit-tag         . "color-160")

    ;; --- Dired ---
    (dired-directory   . "blue")
    (dired-header      . "color-33")
    (dired-symlink     . "color-30")
    (dired-mark        . "red")

    ;; --- Compilation / Grep ---
    (comp-error        . "red")
    (comp-warning      . "color-208")
    (comp-info         . "color-28")
    (comp-line-number  . "color-56")
    (grep-match        . "yellow")
    (grep-file         . "color-56")
    (grep-line         . "color-160")

    ;; --- LSP ---
    (lsp-face-highlight . "color-189")

    ;; --- Calendar ---
    (calendar-today    . "blue")
    (calendar-holiday  . "red")

    ;; --- Speedbar ---
    (speedbar-file     . "color-30")
    (speedbar-dir      . "blue")
    (speedbar-tag      . "color-94")
    (speedbar-selected . "red")
    (speedbar-highlight . "color-254")

    ;; --- Gnus / Message ---
    (gnus-group-1      . "color-33")
    (gnus-group-2      . "color-28")
    (gnus-group-3      . "color-56")
    (gnus-header-from  . "color-30")
    (gnus-header-subject . "blue")
    (gnus-header-name  . "color-94")
    (gnus-header-content . "color-22")
    (gnus-summary-selected . "blue")
    (gnus-summary-normal . "color-236")
    (gnus-cite-1       . "color-30")
    (gnus-cite-2       . "color-28")
    (gnus-cite-3       . "color-56")
    (message-header-name . "color-94")
    (message-header-to   . "color-30")
    (message-header-cc   . "color-22")
    (message-header-other . "color-33")
    (message-header-subject . "blue")
    (message-separator  . "color-246")))

(defun my-theme-palette--dark-256 ()
  "Return the dark 256-color palette alist.
Uses xterm-256 `color-NNN' names for terminals without true color."
  '(;; --- Base ---
    (bg              . "color-234")
    (bg-alt          . "color-235")
    (bg-highlight    . "color-237")
    (bg-region       . "color-60")
    (bg-paren-match  . "color-61")
    (bg-paren-mismatch . "color-52")
    (bg-isearch      . "color-58")
    (bg-lazy-isearch . "color-22")
    (bg-hl-line      . "color-235")
    (fg              . "color-252")
    (fg-alt          . "color-249")
    (fg-dim          . "color-243")
    (fg-faint        . "color-240")
    (cursor          . "color-179")

    ;; --- Syntax ---
    (keyword         . "color-111")
    (string          . "color-149")
    (comment         . "color-60")
    (doc             . "color-107")
    (variable        . "color-141")
    (function-name   . "color-179")
    (type            . "color-44")
    (constant        . "color-209")
    (builtin         . "color-117")
    (preprocessor    . "color-103")
    (negation        . "color-204")
    (warning         . "color-179")
    (error           . "color-204")
    (success         . "color-149")
    (info            . "color-117")

    ;; --- Links ---
    (link            . "color-111")
    (link-visited    . "color-141")

    ;; --- Mode line ---
    (ml-active-bg    . "color-60")
    (ml-active-fg    . "color-252")
    (ml-inactive-bg  . "color-237")
    (ml-inactive-fg  . "color-60")

    ;; --- Diff / VCS ---
    (diff-added-bg   . "color-22")
    (diff-added-fg   . "color-149")
    (diff-removed-bg . "color-52")
    (diff-removed-fg . "color-204")
    (diff-changed-bg . "color-58")
    (diff-changed-fg . "color-179")
    (diff-hunk-bg    . "color-17")
    (diff-hunk-fg    . "color-111")
    (diff-fine-added . "color-28")
    (diff-fine-removed . "color-88")
    (diff-indicator-added . "color-149")
    (diff-indicator-removed . "color-204")

    ;; --- Org mode ---
    (ol1-bg          . "color-237")
    (ol1-fg          . "color-252")
    (ol2-bg          . "color-17")
    (ol2-fg          . "color-111")
    (ol3-bg          . "color-22")
    (ol3-fg          . "color-149")
    (ol4-fg          . "color-204")
    (ol5-fg          . "color-117")
    (ol6-fg          . "color-149")
    (ol7-fg          . "color-209")
    (ol8-fg          . "color-103")
    (org-todo-fg     . "color-204")
    (org-done-fg     . "color-149")
    (org-block-bg    . "color-235")
    (org-code-bg     . "color-236")
    (org-code-fg     . "color-209")
    (org-table-bg    . "color-236")
    (org-date-fg     . "color-141")
    (org-tag-fg      . "color-60")
    (org-drawer-fg   . "color-111")

    ;; --- Outline / Markdown ---
    (outline-1       . "color-252")
    (outline-2       . "color-111")
    (outline-3       . "color-149")
    (outline-4       . "color-204")
    (outline-5       . "color-117")
    (outline-6       . "color-149")
    (outline-7       . "color-209")
    (outline-8       . "color-103")

    ;; --- Company ---
    (company-bg      . "color-235")
    (company-fg      . "color-252")
    (company-sel-bg  . "color-60")
    (company-sel-fg  . "white")
    (company-border  . "color-60")

    ;; --- Flycheck / Flyspell ---
    (flycheck-error-bg . "color-52")
    (flycheck-warn-bg  . "color-58")
    (flycheck-info-bg  . "color-22")

    ;; --- Rainbow delimiters ---
    (rainbow-1       . "color-248")
    (rainbow-2       . "color-111")
    (rainbow-3       . "color-149")
    (rainbow-4       . "color-179")
    (rainbow-5       . "color-204")
    (rainbow-6       . "color-141")
    (rainbow-7       . "color-44")
    (rainbow-8       . "color-209")
    (rainbow-9       . "color-117")

    ;; --- ANSI colors ---
    (ansi-black      . "color-234")
    (ansi-red        . "color-204")
    (ansi-green      . "color-149")
    (ansi-yellow     . "color-179")
    (ansi-blue       . "color-111")
    (ansi-magenta    . "color-141")
    (ansi-cyan       . "color-117")
    (ansi-white      . "color-252")
    (ansi-bright-black   . "color-60")
    (ansi-bright-red     . "color-210")
    (ansi-bright-green   . "color-156")
    (ansi-bright-yellow  . "color-186")
    (ansi-bright-blue    . "color-147")
    (ansi-bright-magenta . "color-183")
    (ansi-bright-cyan    . "color-153")
    (ansi-bright-white   . "white")

    ;; --- OCaml / Tuareg ---
    (tuareg-governing   . "color-117")
    (tuareg-multistage  . "color-141")
    (tuareg-operator    . "color-179")
    (tuareg-module      . "color-141")
    (tuareg-constructor . "color-79")
    (tuareg-label       . "color-179")
    (tuareg-double-semi . "color-209")
    (tuareg-error       . "color-204")
    (tuareg-interactive-output    . "color-149")
    (tuareg-interactive-error     . "color-204")
    (tuareg-interactive-directive . "color-111")
    (tuareg-attribute        . "color-103")
    (tuareg-extension-node   . "color-149")
    (tuareg-doc-markup       . "color-141")
    (tuareg-doc-verbatim     . "color-44")
    (tuareg-line-number      . "color-60")
    (tuareg-opam-error       . "color-204")
    (tuareg-opam-pkg-variable . "color-141")

    ;; --- Merlin ---
    (merlin-type       . "color-17")
    (merlin-warn       . "color-58")
    (merlin-error      . "color-52")

    ;; --- UTop ---
    (utop-prompt       . "color-111")
    (utop-stdout       . "color-252")
    (utop-stderr       . "color-204")
    (utop-frozen       . "color-60")
    (utop-error        . "color-204")

    ;; --- Misc ---
    (shadow            . "color-60")
    (line-number       . "color-239")
    (line-number-current . "color-252")
    (tooltip-bg        . "color-235")
    (tooltip-fg        . "color-252")
    (header-line-bg    . "color-235")
    (header-line-fg    . "color-252")
    (whitespace        . "color-237")
    (trailing-ws       . "color-52")
    (escape-glyph      . "color-209")
    (minibuffer-prompt  . "color-111")
    (fringe            . "color-234")
    (vertical-border   . "color-60")
    (yas-field         . "color-17")

    ;; --- Ediff ---
    (ediff-current-a   . "color-52")
    (ediff-current-b   . "color-22")
    (ediff-current-c   . "color-58")
    (ediff-fine-a      . "color-88")
    (ediff-fine-b      . "color-28")
    (ediff-fine-c      . "color-100")
    (ediff-even        . "color-236")
    (ediff-odd         . "color-237")

    ;; --- Magit ---
    (magit-section-bg  . "color-236")
    (magit-section-fg  . "color-252")
    (magit-branch-local  . "color-111")
    (magit-branch-remote . "color-149")
    (magit-tag         . "color-209")

    ;; --- Dired ---
    (dired-directory   . "color-111")
    (dired-header      . "color-117")
    (dired-symlink     . "color-44")
    (dired-mark        . "color-204")

    ;; --- Compilation / Grep ---
    (comp-error        . "color-204")
    (comp-warning      . "color-179")
    (comp-info         . "color-149")
    (comp-line-number  . "color-141")
    (grep-match        . "color-58")
    (grep-file         . "color-141")
    (grep-line         . "color-209")

    ;; --- LSP ---
    (lsp-face-highlight . "color-17")

    ;; --- Calendar ---
    (calendar-today    . "color-111")
    (calendar-holiday  . "color-204")

    ;; --- Speedbar ---
    (speedbar-file     . "color-179")
    (speedbar-dir      . "color-111")
    (speedbar-tag      . "color-149")
    (speedbar-selected . "color-204")
    (speedbar-highlight . "color-237")

    ;; --- Gnus / Message ---
    (gnus-group-1      . "color-111")
    (gnus-group-2      . "color-149")
    (gnus-group-3      . "color-141")
    (gnus-header-from  . "color-179")
    (gnus-header-subject . "color-111")
    (gnus-header-name  . "color-149")
    (gnus-header-content . "color-44")
    (gnus-summary-selected . "color-111")
    (gnus-summary-normal . "color-252")
    (gnus-cite-1       . "color-179")
    (gnus-cite-2       . "color-149")
    (gnus-cite-3       . "color-141")
    (message-header-name . "color-149")
    (message-header-to   . "color-179")
    (message-header-cc   . "color-44")
    (message-header-other . "color-117")
    (message-header-subject . "color-111")
    (message-separator  . "color-60")))

(defun my-theme-palette--solarized-dark ()
  "Return the Solarized Dark color palette alist.
Uses Ethan Schoonover's canonical Solarized palette."
  '(;; --- Base ---
    (bg              . "#002b36")
    (bg-alt          . "#073642")
    (bg-highlight    . "#0a4050")
    (bg-region       . "#073642")
    (bg-paren-match  . "#0a4a5a")
    (bg-paren-mismatch . "#5c1a1a")
    (bg-isearch      . "#4a4a00")
    (bg-lazy-isearch . "#0a3a1a")
    (bg-hl-line      . "#073642")
    (fg              . "#839496")
    (fg-alt          . "#93a1a1")
    (fg-dim          . "#586e75")
    (fg-faint        . "#465a61")
    (cursor          . "#d33682")

    ;; --- Syntax ---
    (keyword         . "#268bd2")
    (string          . "#2aa198")
    (comment         . "#586e75")
    (doc             . "#6c71c4")
    (variable        . "#d33682")
    (function-name   . "#b58900")
    (type            . "#b58900")
    (constant        . "#cb4b16")
    (builtin         . "#6c71c4")
    (preprocessor    . "#586e75")
    (negation        . "#dc322f")
    (warning         . "#cb4b16")
    (error           . "#dc322f")
    (success         . "#859900")
    (info            . "#268bd2")

    ;; --- Links ---
    (link            . "#268bd2")
    (link-visited    . "#6c71c4")

    ;; --- Mode line ---
    (ml-active-bg    . "#073642")
    (ml-active-fg    . "#eee8d5")
    (ml-inactive-bg  . "#002b36")
    (ml-inactive-fg  . "#586e75")

    ;; --- Diff / VCS ---
    (diff-added-bg   . "#0a2e1a")
    (diff-added-fg   . "#859900")
    (diff-removed-bg . "#2e0a0a")
    (diff-removed-fg . "#dc322f")
    (diff-changed-bg . "#2e2a0a")
    (diff-changed-fg . "#b58900")
    (diff-hunk-bg    . "#003847")
    (diff-hunk-fg    . "#268bd2")
    (diff-fine-added . "#1a4a1a")
    (diff-fine-removed . "#4a1a1a")
    (diff-indicator-added . "#859900")
    (diff-indicator-removed . "#dc322f")

    ;; --- Org mode ---
    (ol1-bg          . "#073642")
    (ol1-fg          . "#eee8d5")
    (ol2-bg          . "#003847")
    (ol2-fg          . "#268bd2")
    (ol3-bg          . "#0a2e1a")
    (ol3-fg          . "#859900")
    (ol4-fg          . "#d33682")
    (ol5-fg          . "#2aa198")
    (ol6-fg          . "#859900")
    (ol7-fg          . "#cb4b16")
    (ol8-fg          . "#586e75")
    (org-todo-fg     . "#dc322f")
    (org-done-fg     . "#859900")
    (org-block-bg    . "#073642")
    (org-code-bg     . "#003340")
    (org-code-fg     . "#cb4b16")
    (org-table-bg    . "#003340")
    (org-date-fg     . "#6c71c4")
    (org-tag-fg      . "#586e75")
    (org-drawer-fg   . "#268bd2")

    ;; --- Outline / Markdown ---
    (outline-1       . "#eee8d5")
    (outline-2       . "#268bd2")
    (outline-3       . "#859900")
    (outline-4       . "#d33682")
    (outline-5       . "#2aa198")
    (outline-6       . "#859900")
    (outline-7       . "#cb4b16")
    (outline-8       . "#586e75")

    ;; --- Company ---
    (company-bg      . "#073642")
    (company-fg      . "#839496")
    (company-sel-bg  . "#0a4a5a")
    (company-sel-fg  . "#eee8d5")
    (company-border  . "#0a4050")

    ;; --- Flycheck / Flyspell ---
    (flycheck-error-bg . "#2e0a0a")
    (flycheck-warn-bg  . "#2e2a0a")
    (flycheck-info-bg  . "#0a2e1a")

    ;; --- Rainbow delimiters ---
    (rainbow-1       . "#839496")
    (rainbow-2       . "#268bd2")
    (rainbow-3       . "#859900")
    (rainbow-4       . "#b58900")
    (rainbow-5       . "#dc322f")
    (rainbow-6       . "#d33682")
    (rainbow-7       . "#6c71c4")
    (rainbow-8       . "#2aa198")
    (rainbow-9       . "#cb4b16")

    ;; --- ANSI colors ---
    (ansi-black      . "#002b36")
    (ansi-red        . "#dc322f")
    (ansi-green      . "#859900")
    (ansi-yellow     . "#b58900")
    (ansi-blue       . "#268bd2")
    (ansi-magenta    . "#d33682")
    (ansi-cyan       . "#2aa198")
    (ansi-white      . "#eee8d5")
    (ansi-bright-black   . "#586e75")
    (ansi-bright-red     . "#ef5350")
    (ansi-bright-green   . "#a0b500")
    (ansi-bright-yellow  . "#d4a017")
    (ansi-bright-blue    . "#4da6e8")
    (ansi-bright-magenta . "#e056a0")
    (ansi-bright-cyan    . "#40c4b4")
    (ansi-bright-white   . "#fdf6e3")

    ;; --- OCaml / Tuareg ---
    (tuareg-governing   . "#268bd2")
    (tuareg-multistage  . "#6c71c4")
    (tuareg-operator    . "#b58900")
    (tuareg-module      . "#6c71c4")
    (tuareg-constructor . "#2aa198")
    (tuareg-label       . "#cb4b16")
    (tuareg-double-semi . "#dc322f")
    (tuareg-error       . "#dc322f")
    (tuareg-interactive-output    . "#859900")
    (tuareg-interactive-error     . "#dc322f")
    (tuareg-interactive-directive . "#268bd2")
    (tuareg-attribute        . "#586e75")
    (tuareg-extension-node   . "#859900")
    (tuareg-doc-markup       . "#d33682")
    (tuareg-doc-verbatim     . "#2aa198")
    (tuareg-line-number      . "#586e75")
    (tuareg-opam-error       . "#dc322f")
    (tuareg-opam-pkg-variable . "#d33682")

    ;; --- Merlin ---
    (merlin-type       . "#003847")
    (merlin-warn       . "#2e2a0a")
    (merlin-error      . "#2e0a0a")

    ;; --- UTop ---
    (utop-prompt       . "#268bd2")
    (utop-stdout       . "#839496")
    (utop-stderr       . "#dc322f")
    (utop-frozen       . "#586e75")
    (utop-error        . "#dc322f")

    ;; --- Misc ---
    (shadow            . "#586e75")
    (line-number       . "#465a61")
    (line-number-current . "#93a1a1")
    (tooltip-bg        . "#073642")
    (tooltip-fg        . "#839496")
    (header-line-bg    . "#073642")
    (header-line-fg    . "#93a1a1")
    (whitespace        . "#0a4050")
    (trailing-ws       . "#4a1a1a")
    (escape-glyph      . "#cb4b16")
    (minibuffer-prompt  . "#268bd2")
    (fringe            . "#002b36")
    (vertical-border   . "#073642")
    (yas-field         . "#003847")

    ;; --- Ediff ---
    (ediff-current-a   . "#2e0a0a")
    (ediff-current-b   . "#0a2e1a")
    (ediff-current-c   . "#2e2a0a")
    (ediff-fine-a      . "#4a1a1a")
    (ediff-fine-b      . "#1a4a1a")
    (ediff-fine-c      . "#4a4a0a")
    (ediff-even        . "#003340")
    (ediff-odd         . "#073642")

    ;; --- Magit ---
    (magit-section-bg  . "#003340")
    (magit-section-fg  . "#839496")
    (magit-branch-local  . "#268bd2")
    (magit-branch-remote . "#859900")
    (magit-tag         . "#cb4b16")

    ;; --- Dired ---
    (dired-directory   . "#268bd2")
    (dired-header      . "#2aa198")
    (dired-symlink     . "#2aa198")
    (dired-mark        . "#dc322f")

    ;; --- Compilation / Grep ---
    (comp-error        . "#dc322f")
    (comp-warning      . "#cb4b16")
    (comp-info         . "#859900")
    (comp-line-number  . "#6c71c4")
    (grep-match        . "#4a4a00")
    (grep-file         . "#6c71c4")
    (grep-line         . "#cb4b16")

    ;; --- LSP ---
    (lsp-face-highlight . "#003847")

    ;; --- Calendar ---
    (calendar-today    . "#268bd2")
    (calendar-holiday  . "#dc322f")

    ;; --- Speedbar ---
    (speedbar-file     . "#b58900")
    (speedbar-dir      . "#268bd2")
    (speedbar-tag      . "#859900")
    (speedbar-selected . "#dc322f")
    (speedbar-highlight . "#073642")

    ;; --- Gnus / Message ---
    (gnus-group-1      . "#268bd2")
    (gnus-group-2      . "#859900")
    (gnus-group-3      . "#6c71c4")
    (gnus-header-from  . "#b58900")
    (gnus-header-subject . "#268bd2")
    (gnus-header-name  . "#859900")
    (gnus-header-content . "#2aa198")
    (gnus-summary-selected . "#268bd2")
    (gnus-summary-normal . "#839496")
    (gnus-cite-1       . "#b58900")
    (gnus-cite-2       . "#859900")
    (gnus-cite-3       . "#6c71c4")
    (message-header-name . "#859900")
    (message-header-to   . "#b58900")
    (message-header-cc   . "#2aa198")
    (message-header-other . "#268bd2")
    (message-header-subject . "#268bd2")
    (message-separator  . "#586e75")))

(defun my-theme-palette--gruvbox-dark ()
  "Return the Gruvbox Dark color palette alist.
Uses morhetz's canonical Gruvbox palette."
  '(;; --- Base ---
    (bg              . "#282828")
    (bg-alt          . "#3c3836")
    (bg-highlight    . "#504945")
    (bg-region       . "#504945")
    (bg-paren-match  . "#665c54")
    (bg-paren-mismatch . "#9d0006")
    (bg-isearch      . "#5a5a00")
    (bg-lazy-isearch . "#1a3a1a")
    (bg-hl-line      . "#3c3836")
    (fg              . "#ebdbb2")
    (fg-alt          . "#d5c4a1")
    (fg-dim          . "#a89984")
    (fg-faint        . "#7c6f64")
    (cursor          . "#fe8019")

    ;; --- Syntax ---
    (keyword         . "#fb4934")
    (string          . "#b8bb26")
    (comment         . "#928374")
    (doc             . "#83a598")
    (variable        . "#83a598")
    (function-name   . "#fabd2f")
    (type            . "#fabd2f")
    (constant        . "#d3869b")
    (builtin         . "#fe8019")
    (preprocessor    . "#928374")
    (negation        . "#fb4934")
    (warning         . "#fe8019")
    (error           . "#fb4934")
    (success         . "#b8bb26")
    (info            . "#83a598")

    ;; --- Links ---
    (link            . "#83a598")
    (link-visited    . "#d3869b")

    ;; --- Mode line ---
    (ml-active-bg    . "#504945")
    (ml-active-fg    . "#ebdbb2")
    (ml-inactive-bg  . "#3c3836")
    (ml-inactive-fg  . "#928374")

    ;; --- Diff / VCS ---
    (diff-added-bg   . "#1a2e1a")
    (diff-added-fg   . "#b8bb26")
    (diff-removed-bg . "#2e1a1a")
    (diff-removed-fg . "#fb4934")
    (diff-changed-bg . "#2e2a1a")
    (diff-changed-fg . "#fabd2f")
    (diff-hunk-bg    . "#3c3836")
    (diff-hunk-fg    . "#83a598")
    (diff-fine-added . "#2a4a2a")
    (diff-fine-removed . "#4a2a2a")
    (diff-indicator-added . "#b8bb26")
    (diff-indicator-removed . "#fb4934")

    ;; --- Org mode ---
    (ol1-bg          . "#3c3836")
    (ol1-fg          . "#ebdbb2")
    (ol2-bg          . "#32302f")
    (ol2-fg          . "#83a598")
    (ol3-bg          . "#1a2e1a")
    (ol3-fg          . "#b8bb26")
    (ol4-fg          . "#fb4934")
    (ol5-fg          . "#83a598")
    (ol6-fg          . "#b8bb26")
    (ol7-fg          . "#fe8019")
    (ol8-fg          . "#928374")
    (org-todo-fg     . "#fb4934")
    (org-done-fg     . "#b8bb26")
    (org-block-bg    . "#3c3836")
    (org-code-bg     . "#32302f")
    (org-code-fg     . "#fe8019")
    (org-table-bg    . "#32302f")
    (org-date-fg     . "#d3869b")
    (org-tag-fg      . "#928374")
    (org-drawer-fg   . "#83a598")

    ;; --- Outline / Markdown ---
    (outline-1       . "#ebdbb2")
    (outline-2       . "#83a598")
    (outline-3       . "#b8bb26")
    (outline-4       . "#fb4934")
    (outline-5       . "#83a598")
    (outline-6       . "#b8bb26")
    (outline-7       . "#fe8019")
    (outline-8       . "#928374")

    ;; --- Company ---
    (company-bg      . "#3c3836")
    (company-fg      . "#ebdbb2")
    (company-sel-bg  . "#504945")
    (company-sel-fg  . "#fbf1c7")
    (company-border  . "#504945")

    ;; --- Flycheck / Flyspell ---
    (flycheck-error-bg . "#2e1a1a")
    (flycheck-warn-bg  . "#2e2a1a")
    (flycheck-info-bg  . "#1a2e1a")

    ;; --- Rainbow delimiters ---
    (rainbow-1       . "#a89984")
    (rainbow-2       . "#fb4934")
    (rainbow-3       . "#b8bb26")
    (rainbow-4       . "#fabd2f")
    (rainbow-5       . "#83a598")
    (rainbow-6       . "#d3869b")
    (rainbow-7       . "#8ec07c")
    (rainbow-8       . "#fe8019")
    (rainbow-9       . "#689d6a")

    ;; --- ANSI colors ---
    (ansi-black      . "#282828")
    (ansi-red        . "#cc241d")
    (ansi-green      . "#98971a")
    (ansi-yellow     . "#d79921")
    (ansi-blue       . "#458588")
    (ansi-magenta    . "#b16286")
    (ansi-cyan       . "#689d6a")
    (ansi-white      . "#a89984")
    (ansi-bright-black   . "#928374")
    (ansi-bright-red     . "#fb4934")
    (ansi-bright-green   . "#b8bb26")
    (ansi-bright-yellow  . "#fabd2f")
    (ansi-bright-blue    . "#83a598")
    (ansi-bright-magenta . "#d3869b")
    (ansi-bright-cyan    . "#8ec07c")
    (ansi-bright-white   . "#ebdbb2")

    ;; --- OCaml / Tuareg ---
    (tuareg-governing   . "#83a598")
    (tuareg-multistage  . "#d3869b")
    (tuareg-operator    . "#fabd2f")
    (tuareg-module      . "#d3869b")
    (tuareg-constructor . "#8ec07c")
    (tuareg-label       . "#fe8019")
    (tuareg-double-semi . "#fb4934")
    (tuareg-error       . "#fb4934")
    (tuareg-interactive-output    . "#b8bb26")
    (tuareg-interactive-error     . "#fb4934")
    (tuareg-interactive-directive . "#83a598")
    (tuareg-attribute        . "#928374")
    (tuareg-extension-node   . "#b8bb26")
    (tuareg-doc-markup       . "#d3869b")
    (tuareg-doc-verbatim     . "#8ec07c")
    (tuareg-line-number      . "#7c6f64")
    (tuareg-opam-error       . "#fb4934")
    (tuareg-opam-pkg-variable . "#d3869b")

    ;; --- Merlin ---
    (merlin-type       . "#3c3836")
    (merlin-warn       . "#2e2a1a")
    (merlin-error      . "#2e1a1a")

    ;; --- UTop ---
    (utop-prompt       . "#83a598")
    (utop-stdout       . "#ebdbb2")
    (utop-stderr       . "#fb4934")
    (utop-frozen       . "#928374")
    (utop-error        . "#fb4934")

    ;; --- Misc ---
    (shadow            . "#928374")
    (line-number       . "#665c54")
    (line-number-current . "#ebdbb2")
    (tooltip-bg        . "#3c3836")
    (tooltip-fg        . "#ebdbb2")
    (header-line-bg    . "#3c3836")
    (header-line-fg    . "#ebdbb2")
    (whitespace        . "#504945")
    (trailing-ws       . "#4a2020")
    (escape-glyph      . "#fe8019")
    (minibuffer-prompt  . "#83a598")
    (fringe            . "#282828")
    (vertical-border   . "#504945")
    (yas-field         . "#3c3836")

    ;; --- Ediff ---
    (ediff-current-a   . "#2e1a1a")
    (ediff-current-b   . "#1a2e1a")
    (ediff-current-c   . "#2e2a1a")
    (ediff-fine-a      . "#4a2a2a")
    (ediff-fine-b      . "#2a4a2a")
    (ediff-fine-c      . "#4a4a1a")
    (ediff-even        . "#32302f")
    (ediff-odd         . "#3c3836")

    ;; --- Magit ---
    (magit-section-bg  . "#32302f")
    (magit-section-fg  . "#ebdbb2")
    (magit-branch-local  . "#83a598")
    (magit-branch-remote . "#b8bb26")
    (magit-tag         . "#fe8019")

    ;; --- Dired ---
    (dired-directory   . "#83a598")
    (dired-header      . "#fabd2f")
    (dired-symlink     . "#8ec07c")
    (dired-mark        . "#fb4934")

    ;; --- Compilation / Grep ---
    (comp-error        . "#fb4934")
    (comp-warning      . "#fe8019")
    (comp-info         . "#b8bb26")
    (comp-line-number  . "#d3869b")
    (grep-match        . "#5a5a00")
    (grep-file         . "#d3869b")
    (grep-line         . "#fe8019")

    ;; --- LSP ---
    (lsp-face-highlight . "#3c3836")

    ;; --- Calendar ---
    (calendar-today    . "#83a598")
    (calendar-holiday  . "#fb4934")

    ;; --- Speedbar ---
    (speedbar-file     . "#fabd2f")
    (speedbar-dir      . "#83a598")
    (speedbar-tag      . "#b8bb26")
    (speedbar-selected . "#fb4934")
    (speedbar-highlight . "#504945")

    ;; --- Gnus / Message ---
    (gnus-group-1      . "#83a598")
    (gnus-group-2      . "#b8bb26")
    (gnus-group-3      . "#d3869b")
    (gnus-header-from  . "#fabd2f")
    (gnus-header-subject . "#83a598")
    (gnus-header-name  . "#b8bb26")
    (gnus-header-content . "#8ec07c")
    (gnus-summary-selected . "#83a598")
    (gnus-summary-normal . "#ebdbb2")
    (gnus-cite-1       . "#fabd2f")
    (gnus-cite-2       . "#b8bb26")
    (gnus-cite-3       . "#d3869b")
    (message-header-name . "#b8bb26")
    (message-header-to   . "#fabd2f")
    (message-header-cc   . "#8ec07c")
    (message-header-other . "#83a598")
    (message-header-subject . "#83a598")
    (message-separator  . "#928374")))

(defun my-theme-palette--dracula ()
  "Return the Dracula color palette alist.
Uses the canonical Dracula palette by Zeno Rocha."
  '(;; --- Base ---
    (bg              . "#282a36")
    (bg-alt          . "#21222c")
    (bg-highlight    . "#44475a")
    (bg-region       . "#44475a")
    (bg-paren-match  . "#555872")
    (bg-paren-mismatch . "#5c1a1a")
    (bg-isearch      . "#5a5a00")
    (bg-lazy-isearch . "#1a3a2a")
    (bg-hl-line      . "#2c2e3e")
    (fg              . "#f8f8f2")
    (fg-alt          . "#bfbfbf")
    (fg-dim          . "#6272a4")
    (fg-faint        . "#4a5078")
    (cursor          . "#f8f8f2")

    ;; --- Syntax ---
    (keyword         . "#ff79c6")
    (string          . "#f1fa8c")
    (comment         . "#6272a4")
    (doc             . "#6272a4")
    (variable        . "#f8f8f2")
    (function-name   . "#50fa7b")
    (type            . "#8be9fd")
    (constant        . "#bd93f9")
    (builtin         . "#ffb86c")
    (preprocessor    . "#6272a4")
    (negation        . "#ff5555")
    (warning         . "#ffb86c")
    (error           . "#ff5555")
    (success         . "#50fa7b")
    (info            . "#8be9fd")

    ;; --- Links ---
    (link            . "#8be9fd")
    (link-visited    . "#bd93f9")

    ;; --- Mode line ---
    (ml-active-bg    . "#44475a")
    (ml-active-fg    . "#f8f8f2")
    (ml-inactive-bg  . "#21222c")
    (ml-inactive-fg  . "#6272a4")

    ;; --- Diff / VCS ---
    (diff-added-bg   . "#1a2e1a")
    (diff-added-fg   . "#50fa7b")
    (diff-removed-bg . "#2e1a1a")
    (diff-removed-fg . "#ff5555")
    (diff-changed-bg . "#2e2a1a")
    (diff-changed-fg . "#ffb86c")
    (diff-hunk-bg    . "#2c2e3e")
    (diff-hunk-fg    . "#bd93f9")
    (diff-fine-added . "#2a4a2a")
    (diff-fine-removed . "#4a2a2a")
    (diff-indicator-added . "#50fa7b")
    (diff-indicator-removed . "#ff5555")

    ;; --- Org mode ---
    (ol1-bg          . "#44475a")
    (ol1-fg          . "#f8f8f2")
    (ol2-bg          . "#2c2e3e")
    (ol2-fg          . "#bd93f9")
    (ol3-bg          . "#1a2e1a")
    (ol3-fg          . "#50fa7b")
    (ol4-fg          . "#ff79c6")
    (ol5-fg          . "#8be9fd")
    (ol6-fg          . "#50fa7b")
    (ol7-fg          . "#ffb86c")
    (ol8-fg          . "#6272a4")
    (org-todo-fg     . "#ff5555")
    (org-done-fg     . "#50fa7b")
    (org-block-bg    . "#21222c")
    (org-code-bg     . "#2c2e3e")
    (org-code-fg     . "#ffb86c")
    (org-table-bg    . "#2c2e3e")
    (org-date-fg     . "#bd93f9")
    (org-tag-fg      . "#6272a4")
    (org-drawer-fg   . "#8be9fd")

    ;; --- Outline / Markdown ---
    (outline-1       . "#f8f8f2")
    (outline-2       . "#bd93f9")
    (outline-3       . "#50fa7b")
    (outline-4       . "#ff79c6")
    (outline-5       . "#8be9fd")
    (outline-6       . "#50fa7b")
    (outline-7       . "#ffb86c")
    (outline-8       . "#6272a4")

    ;; --- Company ---
    (company-bg      . "#21222c")
    (company-fg      . "#f8f8f2")
    (company-sel-bg  . "#44475a")
    (company-sel-fg  . "#f8f8f2")
    (company-border  . "#44475a")

    ;; --- Flycheck / Flyspell ---
    (flycheck-error-bg . "#2e1a1a")
    (flycheck-warn-bg  . "#2e2a1a")
    (flycheck-info-bg  . "#1a2e1a")

    ;; --- Rainbow delimiters ---
    (rainbow-1       . "#f8f8f2")
    (rainbow-2       . "#ff79c6")
    (rainbow-3       . "#50fa7b")
    (rainbow-4       . "#f1fa8c")
    (rainbow-5       . "#bd93f9")
    (rainbow-6       . "#8be9fd")
    (rainbow-7       . "#ffb86c")
    (rainbow-8       . "#ff5555")
    (rainbow-9       . "#6272a4")

    ;; --- ANSI colors ---
    (ansi-black      . "#21222c")
    (ansi-red        . "#ff5555")
    (ansi-green      . "#50fa7b")
    (ansi-yellow     . "#f1fa8c")
    (ansi-blue       . "#bd93f9")
    (ansi-magenta    . "#ff79c6")
    (ansi-cyan       . "#8be9fd")
    (ansi-white      . "#f8f8f2")
    (ansi-bright-black   . "#6272a4")
    (ansi-bright-red     . "#ff6e6e")
    (ansi-bright-green   . "#69ff94")
    (ansi-bright-yellow  . "#ffffa5")
    (ansi-bright-blue    . "#d6acff")
    (ansi-bright-magenta . "#ff92df")
    (ansi-bright-cyan    . "#a4ffff")
    (ansi-bright-white   . "#ffffff")

    ;; --- OCaml / Tuareg ---
    (tuareg-governing   . "#ff79c6")
    (tuareg-multistage  . "#bd93f9")
    (tuareg-operator    . "#f1fa8c")
    (tuareg-module      . "#bd93f9")
    (tuareg-constructor . "#8be9fd")
    (tuareg-label       . "#ffb86c")
    (tuareg-double-semi . "#ff5555")
    (tuareg-error       . "#ff5555")
    (tuareg-interactive-output    . "#50fa7b")
    (tuareg-interactive-error     . "#ff5555")
    (tuareg-interactive-directive . "#bd93f9")
    (tuareg-attribute        . "#6272a4")
    (tuareg-extension-node   . "#50fa7b")
    (tuareg-doc-markup       . "#ff79c6")
    (tuareg-doc-verbatim     . "#8be9fd")
    (tuareg-line-number      . "#4a5078")
    (tuareg-opam-error       . "#ff5555")
    (tuareg-opam-pkg-variable . "#bd93f9")

    ;; --- Merlin ---
    (merlin-type       . "#2c2e3e")
    (merlin-warn       . "#2e2a1a")
    (merlin-error      . "#2e1a1a")

    ;; --- UTop ---
    (utop-prompt       . "#bd93f9")
    (utop-stdout       . "#f8f8f2")
    (utop-stderr       . "#ff5555")
    (utop-frozen       . "#6272a4")
    (utop-error        . "#ff5555")

    ;; --- Misc ---
    (shadow            . "#6272a4")
    (line-number       . "#4a5078")
    (line-number-current . "#f8f8f2")
    (tooltip-bg        . "#21222c")
    (tooltip-fg        . "#f8f8f2")
    (header-line-bg    . "#21222c")
    (header-line-fg    . "#f8f8f2")
    (whitespace        . "#44475a")
    (trailing-ws       . "#4a2020")
    (escape-glyph      . "#ffb86c")
    (minibuffer-prompt  . "#bd93f9")
    (fringe            . "#282a36")
    (vertical-border   . "#44475a")
    (yas-field         . "#2c2e3e")

    ;; --- Ediff ---
    (ediff-current-a   . "#2e1a1a")
    (ediff-current-b   . "#1a2e1a")
    (ediff-current-c   . "#2e2a1a")
    (ediff-fine-a      . "#4a2a2a")
    (ediff-fine-b      . "#2a4a2a")
    (ediff-fine-c      . "#4a4a1a")
    (ediff-even        . "#2c2e3e")
    (ediff-odd         . "#44475a")

    ;; --- Magit ---
    (magit-section-bg  . "#2c2e3e")
    (magit-section-fg  . "#f8f8f2")
    (magit-branch-local  . "#bd93f9")
    (magit-branch-remote . "#50fa7b")
    (magit-tag         . "#ffb86c")

    ;; --- Dired ---
    (dired-directory   . "#bd93f9")
    (dired-header      . "#8be9fd")
    (dired-symlink     . "#8be9fd")
    (dired-mark        . "#ff5555")

    ;; --- Compilation / Grep ---
    (comp-error        . "#ff5555")
    (comp-warning      . "#ffb86c")
    (comp-info         . "#50fa7b")
    (comp-line-number  . "#bd93f9")
    (grep-match        . "#5a5a00")
    (grep-file         . "#bd93f9")
    (grep-line         . "#ffb86c")

    ;; --- LSP ---
    (lsp-face-highlight . "#2c2e3e")

    ;; --- Calendar ---
    (calendar-today    . "#bd93f9")
    (calendar-holiday  . "#ff5555")

    ;; --- Speedbar ---
    (speedbar-file     . "#50fa7b")
    (speedbar-dir      . "#bd93f9")
    (speedbar-tag      . "#8be9fd")
    (speedbar-selected . "#ff5555")
    (speedbar-highlight . "#44475a")

    ;; --- Gnus / Message ---
    (gnus-group-1      . "#bd93f9")
    (gnus-group-2      . "#50fa7b")
    (gnus-group-3      . "#ff79c6")
    (gnus-header-from  . "#50fa7b")
    (gnus-header-subject . "#bd93f9")
    (gnus-header-name  . "#8be9fd")
    (gnus-header-content . "#8be9fd")
    (gnus-summary-selected . "#bd93f9")
    (gnus-summary-normal . "#f8f8f2")
    (gnus-cite-1       . "#50fa7b")
    (gnus-cite-2       . "#8be9fd")
    (gnus-cite-3       . "#ff79c6")
    (message-header-name . "#8be9fd")
    (message-header-to   . "#50fa7b")
    (message-header-cc   . "#8be9fd")
    (message-header-other . "#bd93f9")
    (message-header-subject . "#bd93f9")
    (message-separator  . "#6272a4")))

(defun my-theme-palette--nord ()
  "Return the Nord color palette alist.
Uses Arctic Ice Studio's canonical Nord palette."
  '(;; --- Base ---
    (bg              . "#2e3440")
    (bg-alt          . "#3b4252")
    (bg-highlight    . "#434c5e")
    (bg-region       . "#434c5e")
    (bg-paren-match  . "#4c566a")
    (bg-paren-mismatch . "#5c1a1a")
    (bg-isearch      . "#4a4a00")
    (bg-lazy-isearch . "#1a3a2a")
    (bg-hl-line      . "#3b4252")
    (fg              . "#d8dee9")
    (fg-alt          . "#e5e9f0")
    (fg-dim          . "#81a1c1")
    (fg-faint        . "#4c566a")
    (cursor          . "#d8dee9")

    ;; --- Syntax ---
    (keyword         . "#81a1c1")
    (string          . "#a3be8c")
    (comment         . "#616e88")
    (doc             . "#8fbcbb")
    (variable        . "#d8dee9")
    (function-name   . "#88c0d0")
    (type            . "#8fbcbb")
    (constant        . "#b48ead")
    (builtin         . "#81a1c1")
    (preprocessor    . "#616e88")
    (negation        . "#bf616a")
    (warning         . "#d08770")
    (error           . "#bf616a")
    (success         . "#a3be8c")
    (info            . "#88c0d0")

    ;; --- Links ---
    (link            . "#88c0d0")
    (link-visited    . "#b48ead")

    ;; --- Mode line ---
    (ml-active-bg    . "#434c5e")
    (ml-active-fg    . "#eceff4")
    (ml-inactive-bg  . "#3b4252")
    (ml-inactive-fg  . "#616e88")

    ;; --- Diff / VCS ---
    (diff-added-bg   . "#1a2e1a")
    (diff-added-fg   . "#a3be8c")
    (diff-removed-bg . "#2e1a1a")
    (diff-removed-fg . "#bf616a")
    (diff-changed-bg . "#2e2a1a")
    (diff-changed-fg . "#d08770")
    (diff-hunk-bg    . "#3b4252")
    (diff-hunk-fg    . "#81a1c1")
    (diff-fine-added . "#2a4a2a")
    (diff-fine-removed . "#4a2a2a")
    (diff-indicator-added . "#a3be8c")
    (diff-indicator-removed . "#bf616a")

    ;; --- Org mode ---
    (ol1-bg          . "#3b4252")
    (ol1-fg          . "#eceff4")
    (ol2-bg          . "#353c4a")
    (ol2-fg          . "#81a1c1")
    (ol3-bg          . "#1a2e1a")
    (ol3-fg          . "#a3be8c")
    (ol4-fg          . "#bf616a")
    (ol5-fg          . "#88c0d0")
    (ol6-fg          . "#a3be8c")
    (ol7-fg          . "#d08770")
    (ol8-fg          . "#616e88")
    (org-todo-fg     . "#bf616a")
    (org-done-fg     . "#a3be8c")
    (org-block-bg    . "#3b4252")
    (org-code-bg     . "#353c4a")
    (org-code-fg     . "#d08770")
    (org-table-bg    . "#353c4a")
    (org-date-fg     . "#b48ead")
    (org-tag-fg      . "#616e88")
    (org-drawer-fg   . "#81a1c1")

    ;; --- Outline / Markdown ---
    (outline-1       . "#eceff4")
    (outline-2       . "#81a1c1")
    (outline-3       . "#a3be8c")
    (outline-4       . "#bf616a")
    (outline-5       . "#88c0d0")
    (outline-6       . "#a3be8c")
    (outline-7       . "#d08770")
    (outline-8       . "#616e88")

    ;; --- Company ---
    (company-bg      . "#3b4252")
    (company-fg      . "#d8dee9")
    (company-sel-bg  . "#434c5e")
    (company-sel-fg  . "#eceff4")
    (company-border  . "#434c5e")

    ;; --- Flycheck / Flyspell ---
    (flycheck-error-bg . "#2e1a1a")
    (flycheck-warn-bg  . "#2e2a1a")
    (flycheck-info-bg  . "#1a2e1a")

    ;; --- Rainbow delimiters ---
    (rainbow-1       . "#d8dee9")
    (rainbow-2       . "#81a1c1")
    (rainbow-3       . "#a3be8c")
    (rainbow-4       . "#d08770")
    (rainbow-5       . "#bf616a")
    (rainbow-6       . "#b48ead")
    (rainbow-7       . "#88c0d0")
    (rainbow-8       . "#8fbcbb")
    (rainbow-9       . "#5e81ac")

    ;; --- ANSI colors ---
    (ansi-black      . "#3b4252")
    (ansi-red        . "#bf616a")
    (ansi-green      . "#a3be8c")
    (ansi-yellow     . "#ebcb8b")
    (ansi-blue       . "#81a1c1")
    (ansi-magenta    . "#b48ead")
    (ansi-cyan       . "#88c0d0")
    (ansi-white      . "#e5e9f0")
    (ansi-bright-black   . "#4c566a")
    (ansi-bright-red     . "#d08770")
    (ansi-bright-green   . "#a3be8c")
    (ansi-bright-yellow  . "#ebcb8b")
    (ansi-bright-blue    . "#5e81ac")
    (ansi-bright-magenta . "#b48ead")
    (ansi-bright-cyan    . "#8fbcbb")
    (ansi-bright-white   . "#eceff4")

    ;; --- OCaml / Tuareg ---
    (tuareg-governing   . "#81a1c1")
    (tuareg-multistage  . "#b48ead")
    (tuareg-operator    . "#d08770")
    (tuareg-module      . "#b48ead")
    (tuareg-constructor . "#8fbcbb")
    (tuareg-label       . "#d08770")
    (tuareg-double-semi . "#bf616a")
    (tuareg-error       . "#bf616a")
    (tuareg-interactive-output    . "#a3be8c")
    (tuareg-interactive-error     . "#bf616a")
    (tuareg-interactive-directive . "#81a1c1")
    (tuareg-attribute        . "#616e88")
    (tuareg-extension-node   . "#a3be8c")
    (tuareg-doc-markup       . "#b48ead")
    (tuareg-doc-verbatim     . "#8fbcbb")
    (tuareg-line-number      . "#4c566a")
    (tuareg-opam-error       . "#bf616a")
    (tuareg-opam-pkg-variable . "#b48ead")

    ;; --- Merlin ---
    (merlin-type       . "#3b4252")
    (merlin-warn       . "#2e2a1a")
    (merlin-error      . "#2e1a1a")

    ;; --- UTop ---
    (utop-prompt       . "#81a1c1")
    (utop-stdout       . "#d8dee9")
    (utop-stderr       . "#bf616a")
    (utop-frozen       . "#616e88")
    (utop-error        . "#bf616a")

    ;; --- Misc ---
    (shadow            . "#616e88")
    (line-number       . "#4c566a")
    (line-number-current . "#d8dee9")
    (tooltip-bg        . "#3b4252")
    (tooltip-fg        . "#d8dee9")
    (header-line-bg    . "#3b4252")
    (header-line-fg    . "#d8dee9")
    (whitespace        . "#434c5e")
    (trailing-ws       . "#4a2020")
    (escape-glyph      . "#d08770")
    (minibuffer-prompt  . "#81a1c1")
    (fringe            . "#2e3440")
    (vertical-border   . "#434c5e")
    (yas-field         . "#3b4252")

    ;; --- Ediff ---
    (ediff-current-a   . "#2e1a1a")
    (ediff-current-b   . "#1a2e1a")
    (ediff-current-c   . "#2e2a1a")
    (ediff-fine-a      . "#4a2a2a")
    (ediff-fine-b      . "#2a4a2a")
    (ediff-fine-c      . "#4a4a1a")
    (ediff-even        . "#353c4a")
    (ediff-odd         . "#3b4252")

    ;; --- Magit ---
    (magit-section-bg  . "#353c4a")
    (magit-section-fg  . "#d8dee9")
    (magit-branch-local  . "#81a1c1")
    (magit-branch-remote . "#a3be8c")
    (magit-tag         . "#d08770")

    ;; --- Dired ---
    (dired-directory   . "#81a1c1")
    (dired-header      . "#88c0d0")
    (dired-symlink     . "#8fbcbb")
    (dired-mark        . "#bf616a")

    ;; --- Compilation / Grep ---
    (comp-error        . "#bf616a")
    (comp-warning      . "#d08770")
    (comp-info         . "#a3be8c")
    (comp-line-number  . "#b48ead")
    (grep-match        . "#4a4a00")
    (grep-file         . "#b48ead")
    (grep-line         . "#d08770")

    ;; --- LSP ---
    (lsp-face-highlight . "#3b4252")

    ;; --- Calendar ---
    (calendar-today    . "#81a1c1")
    (calendar-holiday  . "#bf616a")

    ;; --- Speedbar ---
    (speedbar-file     . "#88c0d0")
    (speedbar-dir      . "#81a1c1")
    (speedbar-tag      . "#a3be8c")
    (speedbar-selected . "#bf616a")
    (speedbar-highlight . "#434c5e")

    ;; --- Gnus / Message ---
    (gnus-group-1      . "#81a1c1")
    (gnus-group-2      . "#a3be8c")
    (gnus-group-3      . "#b48ead")
    (gnus-header-from  . "#88c0d0")
    (gnus-header-subject . "#81a1c1")
    (gnus-header-name  . "#a3be8c")
    (gnus-header-content . "#8fbcbb")
    (gnus-summary-selected . "#81a1c1")
    (gnus-summary-normal . "#d8dee9")
    (gnus-cite-1       . "#88c0d0")
    (gnus-cite-2       . "#a3be8c")
    (gnus-cite-3       . "#b48ead")
    (message-header-name . "#a3be8c")
    (message-header-to   . "#88c0d0")
    (message-header-cc   . "#8fbcbb")
    (message-header-other . "#81a1c1")
    (message-header-subject . "#81a1c1")
    (message-separator  . "#616e88")))

(defun my-theme-palette--crt ()
  "Return the CRT phosphor dark color palette alist.
Evokes green (P1) and amber (P3) phosphor monitors from the 1980s."
  '(;; --- Base ---
    (bg              . "#0c0c0c")
    (bg-alt          . "#141414")
    (bg-highlight    . "#1a2a1a")
    (bg-region       . "#1a3a1a")
    (bg-paren-match  . "#2a4a2a")
    (bg-paren-mismatch . "#4a1a1a")
    (bg-isearch      . "#3a5a1a")
    (bg-lazy-isearch . "#1a2a0a")
    (bg-hl-line      . "#111611")
    (fg              . "#33cc33")
    (fg-alt          . "#2aa82a")
    (fg-dim          . "#1a7a1a")
    (fg-faint        . "#145014")
    (cursor          . "#33ff33")

    ;; --- Syntax ---
    (keyword         . "#ffb000")
    (string          . "#44dd44")
    (comment         . "#2a8a2a")
    (doc             . "#339933")
    (variable        . "#66ee66")
    (function-name   . "#ffcc33")
    (type            . "#cc8800")
    (constant        . "#ff9933")
    (builtin         . "#ddaa00")
    (preprocessor    . "#557755")
    (negation        . "#ff3333")
    (warning         . "#ffb000")
    (error           . "#ff3333")
    (success         . "#33ff33")
    (info            . "#ddaa00")

    ;; --- Links ---
    (link            . "#44dd44")
    (link-visited    . "#2a9a2a")

    ;; --- Mode line ---
    (ml-active-bg    . "#1a3a1a")
    (ml-active-fg    . "#33ff33")
    (ml-inactive-bg  . "#141414")
    (ml-inactive-fg  . "#1a7a1a")

    ;; --- Diff / VCS ---
    (diff-added-bg   . "#0a2a0a")
    (diff-added-fg   . "#33ff33")
    (diff-removed-bg . "#2a0a0a")
    (diff-removed-fg . "#ff3333")
    (diff-changed-bg . "#2a2a0a")
    (diff-changed-fg . "#ffb000")
    (diff-hunk-bg    . "#0a1a0a")
    (diff-hunk-fg    . "#33cc33")
    (diff-fine-added . "#1a4a1a")
    (diff-fine-removed . "#4a1a1a")
    (diff-indicator-added . "#33ff33")
    (diff-indicator-removed . "#ff3333")

    ;; --- Org mode ---
    (ol1-bg          . "#1a2a1a")
    (ol1-fg          . "#33ff33")
    (ol2-bg          . "#1a2a0a")
    (ol2-fg          . "#ffcc33")
    (ol3-bg          . "#0a2a1a")
    (ol3-fg          . "#44dd44")
    (ol4-fg          . "#ffb000")
    (ol5-fg          . "#66ee66")
    (ol6-fg          . "#cc8800")
    (ol7-fg          . "#ff9933")
    (ol8-fg          . "#557755")
    (org-todo-fg     . "#ff3333")
    (org-done-fg     . "#33ff33")
    (org-block-bg    . "#0e0e0e")
    (org-code-bg     . "#111611")
    (org-code-fg     . "#ff9933")
    (org-table-bg    . "#111611")
    (org-date-fg     . "#ddaa00")
    (org-tag-fg      . "#1a7a1a")
    (org-drawer-fg   . "#ffb000")

    ;; --- Outline / Markdown ---
    (outline-1       . "#33ff33")
    (outline-2       . "#ffcc33")
    (outline-3       . "#44dd44")
    (outline-4       . "#ffb000")
    (outline-5       . "#66ee66")
    (outline-6       . "#cc8800")
    (outline-7       . "#ff9933")
    (outline-8       . "#557755")

    ;; --- Company ---
    (company-bg      . "#141414")
    (company-fg      . "#33cc33")
    (company-sel-bg  . "#1a3a1a")
    (company-sel-fg  . "#33ff33")
    (company-border  . "#1a3a1a")

    ;; --- Flycheck / Flyspell ---
    (flycheck-error-bg . "#2a0a0a")
    (flycheck-warn-bg  . "#2a2a0a")
    (flycheck-info-bg  . "#0a2a0a")

    ;; --- Rainbow delimiters ---
    (rainbow-1       . "#33cc33")
    (rainbow-2       . "#ffb000")
    (rainbow-3       . "#44dd44")
    (rainbow-4       . "#cc8800")
    (rainbow-5       . "#66ee66")
    (rainbow-6       . "#ffcc33")
    (rainbow-7       . "#2aa82a")
    (rainbow-8       . "#ff9933")
    (rainbow-9       . "#ddaa00")

    ;; --- ANSI colors ---
    (ansi-black      . "#0c0c0c")
    (ansi-red        . "#cc3333")
    (ansi-green      . "#33cc33")
    (ansi-yellow     . "#ccaa00")
    (ansi-blue       . "#338833")
    (ansi-magenta    . "#aa6600")
    (ansi-cyan       . "#44aa44")
    (ansi-white      . "#33cc33")
    (ansi-bright-black   . "#1a7a1a")
    (ansi-bright-red     . "#ff3333")
    (ansi-bright-green   . "#33ff33")
    (ansi-bright-yellow  . "#ffcc33")
    (ansi-bright-blue    . "#44dd44")
    (ansi-bright-magenta . "#ffb000")
    (ansi-bright-cyan    . "#66ee66")
    (ansi-bright-white   . "#77ff77")

    ;; --- OCaml / Tuareg ---
    (tuareg-governing   . "#ffb000")
    (tuareg-multistage  . "#cc8800")
    (tuareg-operator    . "#ddaa00")
    (tuareg-module      . "#ffcc33")
    (tuareg-constructor . "#44dd44")
    (tuareg-label       . "#ff9933")
    (tuareg-double-semi . "#ff6633")
    (tuareg-error       . "#ff3333")
    (tuareg-interactive-output    . "#33cc33")
    (tuareg-interactive-error     . "#ff3333")
    (tuareg-interactive-directive . "#ffb000")
    (tuareg-attribute        . "#557755")
    (tuareg-extension-node   . "#44dd44")
    (tuareg-doc-markup       . "#cc8800")
    (tuareg-doc-verbatim     . "#339933")
    (tuareg-line-number      . "#1a7a1a")
    (tuareg-opam-error       . "#ff3333")
    (tuareg-opam-pkg-variable . "#66ee66")

    ;; --- Merlin ---
    (merlin-type       . "#1a2a1a")
    (merlin-warn       . "#2a2a0a")
    (merlin-error      . "#2a0a0a")

    ;; --- UTop ---
    (utop-prompt       . "#ffb000")
    (utop-stdout       . "#33cc33")
    (utop-stderr       . "#ff3333")
    (utop-frozen       . "#1a7a1a")
    (utop-error        . "#ff3333")

    ;; --- Misc ---
    (shadow            . "#1a7a1a")
    (line-number       . "#145014")
    (line-number-current . "#33cc33")
    (tooltip-bg        . "#141414")
    (tooltip-fg        . "#33cc33")
    (header-line-bg    . "#141414")
    (header-line-fg    . "#33cc33")
    (whitespace        . "#1a1a1a")
    (trailing-ws       . "#4a1a1a")
    (escape-glyph      . "#ff9933")
    (minibuffer-prompt  . "#ffb000")
    (fringe            . "#0c0c0c")
    (vertical-border   . "#1a3a1a")
    (yas-field         . "#1a2a0a")

    ;; --- Ediff ---
    (ediff-current-a   . "#2a0a0a")
    (ediff-current-b   . "#0a2a0a")
    (ediff-current-c   . "#2a2a0a")
    (ediff-fine-a      . "#4a1a1a")
    (ediff-fine-b      . "#1a4a1a")
    (ediff-fine-c      . "#4a4a0a")
    (ediff-even        . "#111611")
    (ediff-odd         . "#1a1a1a")

    ;; --- Magit ---
    (magit-section-bg  . "#111611")
    (magit-section-fg  . "#33cc33")
    (magit-branch-local  . "#ffb000")
    (magit-branch-remote . "#33ff33")
    (magit-tag         . "#ff9933")

    ;; --- Dired ---
    (dired-directory   . "#ffb000")
    (dired-header      . "#ffcc33")
    (dired-symlink     . "#44dd44")
    (dired-mark        . "#ff3333")

    ;; --- Compilation / Grep ---
    (comp-error        . "#ff3333")
    (comp-warning      . "#ffb000")
    (comp-info         . "#33ff33")
    (comp-line-number  . "#ddaa00")
    (grep-match        . "#3a5a1a")
    (grep-file         . "#ddaa00")
    (grep-line         . "#ff9933")

    ;; --- LSP ---
    (lsp-face-highlight . "#1a2a1a")

    ;; --- Calendar ---
    (calendar-today    . "#ffb000")
    (calendar-holiday  . "#ff3333")

    ;; --- Speedbar ---
    (speedbar-file     . "#33cc33")
    (speedbar-dir      . "#ffb000")
    (speedbar-tag      . "#44dd44")
    (speedbar-selected . "#33ff33")
    (speedbar-highlight . "#1a2a1a")

    ;; --- Gnus / Message ---
    (gnus-group-1      . "#ffb000")
    (gnus-group-2      . "#33ff33")
    (gnus-group-3      . "#cc8800")
    (gnus-header-from  . "#ffcc33")
    (gnus-header-subject . "#ffb000")
    (gnus-header-name  . "#44dd44")
    (gnus-header-content . "#339933")
    (gnus-summary-selected . "#ffb000")
    (gnus-summary-normal . "#33cc33")
    (gnus-cite-1       . "#ffcc33")
    (gnus-cite-2       . "#44dd44")
    (gnus-cite-3       . "#cc8800")
    (message-header-name . "#44dd44")
    (message-header-to   . "#ffcc33")
    (message-header-cc   . "#339933")
    (message-header-other . "#ddaa00")
    (message-header-subject . "#ffb000")
    (message-separator  . "#1a7a1a")))

(defun my-theme-palette--tron ()
  "Return the Tron Legacy dark color palette alist.
Inspired by the Tron universe — deep black with electric cyan and orange."
  '(;; --- Base ---
    (bg              . "#0a0a0f")
    (bg-alt          . "#0f1117")
    (bg-highlight    . "#0f1a2a")
    (bg-region       . "#0f2a4a")
    (bg-paren-match  . "#0f3a5a")
    (bg-paren-mismatch . "#4a0f0f")
    (bg-isearch      . "#1a3a5a")
    (bg-lazy-isearch . "#0f1a2a")
    (bg-hl-line      . "#0c0e14")
    (fg              . "#c0d0e0")
    (fg-alt          . "#8090a0")
    (fg-dim          . "#506070")
    (fg-faint        . "#354050")
    (cursor          . "#6fc3df")

    ;; --- Syntax ---
    (keyword         . "#6fc3df")
    (string          . "#7fbf5f")
    (comment         . "#405060")
    (doc             . "#5a8a5a")
    (variable        . "#8fd4e8")
    (function-name   . "#df740c")
    (type            . "#4fafcf")
    (constant        . "#df740c")
    (builtin         . "#5fbfdf")
    (preprocessor    . "#506878")
    (negation        . "#df3030")
    (warning         . "#df740c")
    (error           . "#df3030")
    (success         . "#33ff33")
    (info            . "#6fc3df")

    ;; --- Links ---
    (link            . "#6fc3df")
    (link-visited    . "#4f8faf")

    ;; --- Mode line ---
    (ml-active-bg    . "#0f2a4a")
    (ml-active-fg    . "#6fc3df")
    (ml-inactive-bg  . "#0f1117")
    (ml-inactive-fg  . "#405060")

    ;; --- Diff / VCS ---
    (diff-added-bg   . "#0a1f0a")
    (diff-added-fg   . "#33ff33")
    (diff-removed-bg . "#2a0a0a")
    (diff-removed-fg . "#df3030")
    (diff-changed-bg . "#1a1a0a")
    (diff-changed-fg . "#df740c")
    (diff-hunk-bg    . "#0a0f1a")
    (diff-hunk-fg    . "#6fc3df")
    (diff-fine-added . "#1a3a1a")
    (diff-fine-removed . "#3a1a1a")
    (diff-indicator-added . "#33ff33")
    (diff-indicator-removed . "#df3030")

    ;; --- Org mode ---
    (ol1-bg          . "#0f1a2a")
    (ol1-fg          . "#6fc3df")
    (ol2-bg          . "#0f1117")
    (ol2-fg          . "#df740c")
    (ol3-bg          . "#0a1a0f")
    (ol3-fg          . "#7fbf5f")
    (ol4-fg          . "#df3030")
    (ol5-fg          . "#8fd4e8")
    (ol6-fg          . "#5fbfdf")
    (ol7-fg          . "#df740c")
    (ol8-fg          . "#506878")
    (org-todo-fg     . "#df3030")
    (org-done-fg     . "#33ff33")
    (org-block-bg    . "#0c0e14")
    (org-code-bg     . "#0f1117")
    (org-code-fg     . "#df740c")
    (org-table-bg    . "#0f1117")
    (org-date-fg     . "#5fbfdf")
    (org-tag-fg      . "#405060")
    (org-drawer-fg   . "#6fc3df")

    ;; --- Outline / Markdown ---
    (outline-1       . "#6fc3df")
    (outline-2       . "#df740c")
    (outline-3       . "#7fbf5f")
    (outline-4       . "#df3030")
    (outline-5       . "#8fd4e8")
    (outline-6       . "#5fbfdf")
    (outline-7       . "#df740c")
    (outline-8       . "#506878")

    ;; --- Company ---
    (company-bg      . "#0f1117")
    (company-fg      . "#c0d0e0")
    (company-sel-bg  . "#0f2a4a")
    (company-sel-fg  . "#6fc3df")
    (company-border  . "#0f2a4a")

    ;; --- Flycheck / Flyspell ---
    (flycheck-error-bg . "#2a0a0a")
    (flycheck-warn-bg  . "#1a1a0a")
    (flycheck-info-bg  . "#0a1f0a")

    ;; --- Rainbow delimiters ---
    (rainbow-1       . "#6fc3df")
    (rainbow-2       . "#df740c")
    (rainbow-3       . "#7fbf5f")
    (rainbow-4       . "#8fd4e8")
    (rainbow-5       . "#df3030")
    (rainbow-6       . "#5fbfdf")
    (rainbow-7       . "#4fafcf")
    (rainbow-8       . "#df8f3c")
    (rainbow-9       . "#c0d0e0")

    ;; --- ANSI colors ---
    (ansi-black      . "#0a0a0f")
    (ansi-red        . "#df3030")
    (ansi-green      . "#33cc33")
    (ansi-yellow     . "#df740c")
    (ansi-blue       . "#4f8faf")
    (ansi-magenta    . "#8f5faf")
    (ansi-cyan       . "#6fc3df")
    (ansi-white      . "#c0d0e0")
    (ansi-bright-black   . "#506070")
    (ansi-bright-red     . "#ff5050")
    (ansi-bright-green   . "#33ff33")
    (ansi-bright-yellow  . "#ff9933")
    (ansi-bright-blue    . "#6fc3df")
    (ansi-bright-magenta . "#af7fdf")
    (ansi-bright-cyan    . "#8fd4e8")
    (ansi-bright-white   . "#e0f0ff")

    ;; --- OCaml / Tuareg ---
    (tuareg-governing   . "#6fc3df")
    (tuareg-multistage  . "#8f5faf")
    (tuareg-operator    . "#df740c")
    (tuareg-module      . "#4fafcf")
    (tuareg-constructor . "#8fd4e8")
    (tuareg-label       . "#df8f3c")
    (tuareg-double-semi . "#df3030")
    (tuareg-error       . "#df3030")
    (tuareg-interactive-output    . "#33cc33")
    (tuareg-interactive-error     . "#df3030")
    (tuareg-interactive-directive . "#6fc3df")
    (tuareg-attribute        . "#506878")
    (tuareg-extension-node   . "#7fbf5f")
    (tuareg-doc-markup       . "#8f5faf")
    (tuareg-doc-verbatim     . "#5fbfdf")
    (tuareg-line-number      . "#405060")
    (tuareg-opam-error       . "#df3030")
    (tuareg-opam-pkg-variable . "#8fd4e8")

    ;; --- Merlin ---
    (merlin-type       . "#0f1a2a")
    (merlin-warn       . "#1a1a0a")
    (merlin-error      . "#2a0a0a")

    ;; --- UTop ---
    (utop-prompt       . "#6fc3df")
    (utop-stdout       . "#c0d0e0")
    (utop-stderr       . "#df3030")
    (utop-frozen       . "#405060")
    (utop-error        . "#df3030")

    ;; --- Misc ---
    (shadow            . "#405060")
    (line-number       . "#253040")
    (line-number-current . "#c0d0e0")
    (tooltip-bg        . "#0f1117")
    (tooltip-fg        . "#c0d0e0")
    (header-line-bg    . "#0f1117")
    (header-line-fg    . "#c0d0e0")
    (whitespace        . "#151520")
    (trailing-ws       . "#3a1a1a")
    (escape-glyph      . "#df740c")
    (minibuffer-prompt  . "#6fc3df")
    (fringe            . "#0a0a0f")
    (vertical-border   . "#0f2a4a")
    (yas-field         . "#0f1a2a")

    ;; --- Ediff ---
    (ediff-current-a   . "#2a0a0a")
    (ediff-current-b   . "#0a1f0a")
    (ediff-current-c   . "#1a1a0a")
    (ediff-fine-a      . "#3a1a1a")
    (ediff-fine-b      . "#1a3a1a")
    (ediff-fine-c      . "#3a3a0a")
    (ediff-even        . "#0c0e14")
    (ediff-odd         . "#0f1117")

    ;; --- Magit ---
    (magit-section-bg  . "#0c0e14")
    (magit-section-fg  . "#c0d0e0")
    (magit-branch-local  . "#6fc3df")
    (magit-branch-remote . "#33cc33")
    (magit-tag         . "#df740c")

    ;; --- Dired ---
    (dired-directory   . "#6fc3df")
    (dired-header      . "#8fd4e8")
    (dired-symlink     . "#5fbfdf")
    (dired-mark        . "#df3030")

    ;; --- Compilation / Grep ---
    (comp-error        . "#df3030")
    (comp-warning      . "#df740c")
    (comp-info         . "#33cc33")
    (comp-line-number  . "#5fbfdf")
    (grep-match        . "#1a3a5a")
    (grep-file         . "#5fbfdf")
    (grep-line         . "#df740c")

    ;; --- LSP ---
    (lsp-face-highlight . "#0f1a2a")

    ;; --- Calendar ---
    (calendar-today    . "#6fc3df")
    (calendar-holiday  . "#df3030")

    ;; --- Speedbar ---
    (speedbar-file     . "#c0d0e0")
    (speedbar-dir      . "#6fc3df")
    (speedbar-tag      . "#7fbf5f")
    (speedbar-selected . "#df740c")
    (speedbar-highlight . "#0f1a2a")

    ;; --- Gnus / Message ---
    (gnus-group-1      . "#6fc3df")
    (gnus-group-2      . "#33cc33")
    (gnus-group-3      . "#8f5faf")
    (gnus-header-from  . "#df740c")
    (gnus-header-subject . "#6fc3df")
    (gnus-header-name  . "#7fbf5f")
    (gnus-header-content . "#5fbfdf")
    (gnus-summary-selected . "#6fc3df")
    (gnus-summary-normal . "#c0d0e0")
    (gnus-cite-1       . "#6fc3df")
    (gnus-cite-2       . "#7fbf5f")
    (gnus-cite-3       . "#8f5faf")
    (message-header-name . "#7fbf5f")
    (message-header-to   . "#df740c")
    (message-header-cc   . "#5fbfdf")
    (message-header-other . "#8fd4e8")
    (message-header-subject . "#6fc3df")
    (message-separator  . "#405060")))

(defun my-theme-palette (variant)
  "Return a color palette alist for VARIANT.
VARIANT is a symbol: `light', `dark', `light-256', `dark-256',
`solarized-dark', `gruvbox-dark', `dracula', `nord', `crt', or `tron'."
  (pcase variant
    ('light          (my-theme-palette--light))
    ('dark           (my-theme-palette--dark))
    ('light-256      (my-theme-palette--light-256))
    ('dark-256       (my-theme-palette--dark-256))
    ('solarized-dark (my-theme-palette--solarized-dark))
    ('gruvbox-dark   (my-theme-palette--gruvbox-dark))
    ('dracula        (my-theme-palette--dracula))
    ('nord           (my-theme-palette--nord))
    ('crt            (my-theme-palette--crt))
    ('tron           (my-theme-palette--tron))
    (_ (error "Unknown theme variant: %s" variant))))

(defun my-theme-palette-keys ()
  "Return the list of semantic color names (keys) in the palette.
Both variants are guaranteed to share the same keys."
  (mapcar #'car (my-theme-palette--light)))

(provide 'my-theme-palette)
;;; my-theme-palette.el ends here
